image: chilio/laravel-dusk-ci:php-8.2

stages:
  - test

unit_test:
  stage: test
  script:
    - apt-get update && apt-get install -y php8.2-mailparse
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - vendor/bin/phpunit

test_coverage:
  stage: test
  script:
    - apt-get update && apt-get install -y php8.2-mailparse
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - vendor/bin/phpunit --coverage-text --colors=never

test_coding_standard:
  stage: test
  script:
    - apt-get update && apt-get install -y php8.2-mailparse
    - cp .env.example .env
    - composer install
    - vendor/bin/phpcs . --ignore="*/vendor/*,*/node_modules/*,*/public/*,*/database/*,*/autoload.php,*/cache/*,*/*.blade.php,*/storage/*,*/tests/*" --standard=PSR2

browser_test:
  stage: test
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: homestead
    DB_HOST: mysql
    DB_CONNECTION: mysql
  services:
    - mysql:5.7
  script:
    - apt-get update && apt-get install -y php8.2-mailparse
    - cp .env.dusk.ci .env
    - composer install
    - configure-laravel
    - start-nginx-ci-project
    - php artisan mailcare:email-receive tests/storage/email_with_attachment.eml
    - chmod -R 777 storage/app/emails/
    - php artisan dusk --colors --env=dusk.ci

  artifacts:
    paths:
      - ./storage/logs
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always
