name: GitLab to GitHub Sync

on:
  push:
    branches:
      - master
      - actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitLab repository
      run: |
        git clone https://gitlab.com/mailcare/mailcare.git
        cd mailcare
        git checkout master
        cd ..
      continue-on-error: false

    - name: Checkout GitHub repository
      uses: actions/checkout@v2
      with:
        repository: lazarivkovic/mailcare
        ref: actions

    - name: Sync changes
      run: |
        rsync -a mailcare/ lazarivkovic/mailcare/
      continue-on-error: false

    - name: Push changes to GitHub
      run: |
        cd lazarivkovic/mailcare
        git add .
        git commit -m "Sync with GitLab"
        git push origin actions
      continue-on-error: false
