name: GitLab to GitHub Sync

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2
      with:
        ref: actions

    - name: Merge changes from GitLab
      run: |
        git remote add gitlab https://gitlab.com/mailcare/mailcare.git
        git fetch gitlab master
        git checkout actions
        git merge gitlab/master --no-commit
        git commit -m "Sync with GitLab"
        git push
      continue-on-error: true
